<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_create_account</name>
   <tag></tag>
   <elementGuidId>2fda2e77-50ee-411a-8579-b9dd26eecea2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>c534f3b8-d259-494c-96a6-447f368a933e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='PopUp']//div[@class='login ng-scope']//a[2]</value>
      <webElementGuid>0ef7b585-22a6-4e21-9a6d-3e00546fa596</webElementGuid>
   </webElementProperties>
</WebElementEntity>
