<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_login_remember_me</name>
   <tag></tag>
   <elementGuidId>f5e240e9-43c9-477e-ab19-7ddf428da361</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>3e79f13e-53e5-45e9-8044-5948ef85d1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='remember_me']</value>
      <webElementGuid>81ec0bc3-1a13-4842-84ca-e121c8b4e596</webElementGuid>
   </webElementProperties>
</WebElementEntity>
