<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_agree</name>
   <tag></tag>
   <elementGuidId>50925f3b-2f62-4703-8bc7-30192432f6c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>214c402b-834f-4bdd-b7f5-a9dfcc92e73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='i_agree']</value>
      <webElementGuid>b4ba8611-c5e3-4267-b766-55e19c93da0c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
