<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_login_username</name>
   <tag></tag>
   <elementGuidId>ec4d6f99-aebf-45a6-a3d4-8ef785073f67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>349276d5-e9fa-4fbb-b599-6b1d3bdc2329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='username']</value>
      <webElementGuid>6e0cef39-8313-4d9f-a3fa-2aa16958ab37</webElementGuid>
   </webElementProperties>
</WebElementEntity>
