<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_user_name</name>
   <tag></tag>
   <elementGuidId>4386fa16-d1d7-44eb-8592-f95a424fbce8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>a64d93aa-e733-4dfa-915f-ce84c8e5abc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='menuUserLink']//span</value>
      <webElementGuid>c9a8c5a9-96bb-4b66-988c-c804468195b4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
