<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Shopping</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d38c5c5d-ae2a-478f-b774-1009114c8699</testSuiteGuid>
   <testCaseLink>
      <guid>1e5d1814-ffa2-49b0-9d57-a3876919893b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Final Project - Website/Positive Test/Shopping/checkout_test</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8d52d3d-b0d9-4d2b-9eaa-653815ef3e3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>417b7302-4b7c-474f-8fc0-77c8d7d22c00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4ea9e6e-233e-4ca4-ad47-f13bd1e6d502</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9597a4f2-52c5-474c-af3e-489eae4168c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74df7ec5-f27a-43cc-bf90-cc2bf731cd90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73df91db-6cf7-4782-a963-1c77e14899a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64ab408b-5a8e-4f2a-a125-760b7b76db91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75dd1924-b7d1-4bab-9f5d-bd3f0c765b23</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b3731eb8-9d8b-4030-817d-06c8dbb75bad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Final Project - Website/Positive Test/Shopping/filter_search_test</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>dec88d86-aada-4cfd-93f6-3a408a9c68ef</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Filter Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>dec88d86-aada-4cfd-93f6-3a408a9c68ef</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>manufacturer</value>
         <variableId>9aad766c-5de9-47e4-b07d-a2b8f20d067d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dec88d86-aada-4cfd-93f6-3a408a9c68ef</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>color</value>
         <variableId>d5317d02-f8fc-4188-b70b-8605b435b5f5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
