<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_shopping_cart</name>
   <tag></tag>
   <elementGuidId>a4534c0a-3de2-4d6a-a946-a4b1c7571b96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id='shoppingCartLink']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>db96517a-ff2c-4702-8dc8-61828aaa4ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='shoppingCartLink']</value>
      <webElementGuid>8db03370-aaba-482a-8d0b-3cfcfb719a7f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
