<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_mastercredit_paynow</name>
   <tag></tag>
   <elementGuidId>60825e28-3571-4ec5-882b-32dd00154dbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>50bde57f-1b5b-4469-9f0e-4059095e9f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='pay_now_btn_ManualPayment']</value>
      <webElementGuid>15edf443-a517-4e59-bec3-f050e8f24691</webElementGuid>
   </webElementProperties>
</WebElementEntity>
