<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_color_blue</name>
   <tag></tag>
   <elementGuidId>5ff5f6ee-3927-47d8-b9da-fc88403120c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>de81c149-9db8-45ff-9e76-c1698800d4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@title='BLUE']</value>
      <webElementGuid>ba3f3ec7-36b0-4137-b41f-375a4fd96d73</webElementGuid>
   </webElementProperties>
</WebElementEntity>
