<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_color_white</name>
   <tag></tag>
   <elementGuidId>5e742665-8895-43ac-9064-7f3798f8638f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>3be49b68-ba3c-4f2e-9f70-4a834162bf1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@title='WHITE']</value>
      <webElementGuid>4ae74615-ba3f-4ab4-9b5c-32f2f3834922</webElementGuid>
   </webElementProperties>
</WebElementEntity>
