<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_next</name>
   <tag></tag>
   <elementGuidId>3faf6273-bd9f-41d2-ac72-396c28e7757e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>0893e06f-6537-4d18-a341-098f9bf4c1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//button[@id='next_btn'])[position()=1]</value>
      <webElementGuid>93625558-3c9d-4d31-b9a0-e0d3afe88d2b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
