<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_color</name>
   <tag></tag>
   <elementGuidId>85ade1c1-2c17-42e8-9ca9-47c669e9be46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>cecff699-4c42-4f3a-99f3-6939df168996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h4[@id='accordionColor']</value>
      <webElementGuid>ff8b7c6b-773b-4363-b75f-c7924c4d0815</webElementGuid>
   </webElementProperties>
</WebElementEntity>
