<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_buy_now</name>
   <tag></tag>
   <elementGuidId>ff32022e-3f6f-4728-92fc-c1d7d2af8485</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>2cf73ad0-64f8-469d-a050-16c06654b8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@name='buy_now']</value>
      <webElementGuid>07f6fa64-3fa4-4ace-b654-c6ff72607f4a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
