<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_mastercredit_edit</name>
   <tag></tag>
   <elementGuidId>973f1329-7615-420a-8ef5-63c073168ccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>5f280d3d-2912-4586-b67a-36ea26d80cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='masterCreditSeccion']//label</value>
      <webElementGuid>f1ac07df-d970-4341-8f35-04596659d01d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
