<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_bose</name>
   <tag></tag>
   <elementGuidId>14b54c98-4d0d-4d0f-92e0-6334d1b3a98f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>a5e07ebb-df8e-4078-bb23-a27ec7cc811c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='manufacturer_0']</value>
      <webElementGuid>9d512864-15ab-479d-869b-4115521b5e5c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
