<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_logitech</name>
   <tag></tag>
   <elementGuidId>3c4107f5-e0f2-4c34-ae42-083872fe7b20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>2bad2337-81e5-48db-ba01-5930dbacbbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='manufacturer_2']</value>
      <webElementGuid>6743958c-d384-47ef-84e1-a16e92351475</webElementGuid>
   </webElementProperties>
</WebElementEntity>
