<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_order_success</name>
   <tag></tag>
   <elementGuidId>f3d34a74-2b03-47dd-9fe4-a8b3a306b471</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>b7f81823-9a1b-4909-a7dc-3ec9c5f3ec6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='orderPaymentSuccess']</value>
      <webElementGuid>84500974-6780-4a54-90f7-32a832ea9557</webElementGuid>
   </webElementProperties>
</WebElementEntity>
