<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_item_speaker</name>
   <tag></tag>
   <elementGuidId>38536f8e-a257-498e-9036-62a993b954ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>c0afa5ba-276e-47a8-91a6-569c54fd3168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='speakersImg']</value>
      <webElementGuid>4c77aa01-f71c-430d-8c26-5003d992db5e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
