<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_safepay_username</name>
   <tag></tag>
   <elementGuidId>eb797515-411b-44bf-b1ab-31b924dc2c0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>01b3c088-a037-417b-9b52-8e0029c49227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='safepay_username']</value>
      <webElementGuid>b4c2f5fd-c13f-4794-a0fc-e9f3446196d7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
