<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_safepay_password</name>
   <tag></tag>
   <elementGuidId>05280f8c-7669-4310-920c-3a42d9d549d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>a4598204-2f62-4d8c-ad66-a18de0076d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='safepay_password']</value>
      <webElementGuid>c1c54075-ad3d-41fc-b733-a9969cca1500</webElementGuid>
   </webElementProperties>
</WebElementEntity>
