<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mastercredit_cvv_number</name>
   <tag></tag>
   <elementGuidId>9f88aae3-6f4b-4e79-9232-23184f280130</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>57b709d3-ee61-4e7b-a025-2eb98ea6e3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='cvv_number']</value>
      <webElementGuid>ac913fdf-bbda-4ab7-8858-ff4bdb754a9f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
