<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mastercredit_card_number</name>
   <tag></tag>
   <elementGuidId>e65941f9-d874-4cc7-b986-8dc3df088454</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>23c24ac9-8557-47ff-b6db-531cfb51c3d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='card_number']</value>
      <webElementGuid>b789e134-1d8c-4ef9-8e49-9e0f68ce62ea</webElementGuid>
   </webElementProperties>
</WebElementEntity>
