<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mastercredit_name</name>
   <tag></tag>
   <elementGuidId>3f10d8cf-e9f5-4e9d-ae69-717bb63c0877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>b5e3b8b8-522a-4720-a0ba-4d3f49f8af0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='cardholder_name']</value>
      <webElementGuid>3176645c-a5da-42cf-9310-a65580bc5839</webElementGuid>
   </webElementProperties>
</WebElementEntity>
