<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_safepay</name>
   <tag></tag>
   <elementGuidId>3a012eab-5419-4c37-ac1d-951349ab0cce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>eb822e94-6d36-48c7-8fbd-574f6753cac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='safepay']</value>
      <webElementGuid>f9162b04-e7b7-4446-bb1f-ac67567b194c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
