<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_master_credit</name>
   <tag></tag>
   <elementGuidId>804b71c3-c3cf-42b9-8bd1-6300e5e1c4b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>0f65d3b8-1159-4434-af37-83487713aedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='masterCredit']</value>
      <webElementGuid>537ead84-d6b0-4e51-b05f-7fe71a8ec95f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
