<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_mastercredit_exp_month</name>
   <tag></tag>
   <elementGuidId>5d1bb926-aa99-4bf1-b0ce-95971f504838</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>f150a3a4-8e76-47df-a1d8-f0738d987a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@name='mmListbox']</value>
      <webElementGuid>5376baf1-e266-4040-89e5-d51eefb78a8e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
